/**
 * 游客模式展示数据
 * 纯前端本地数据，不需要数据库连接
 * 让新用户在注册前就能体验完整功能
 *
 * 家庭设定：
 * - 小明：小学三年级男生，9岁
 * - 小红：初中一年级女生，13岁
 */
import { Task, Member, Reward, HistoryRecord } from '../types';

const now = new Date();
const today = now.toISOString().split('T')[0];
const tomorrow = new Date(now.getTime() + 86400000).toISOString().split('T')[0];
const yesterday = new Date(now.getTime() - 86400000).toISOString().split('T')[0];
const nextWeek = new Date(now.getTime() + 86400000 * 7).toISOString().split('T')[0];

// ========== 游客家庭成员 ==========
export const GUEST_MEMBERS: Member[] = [
  {
    id: 'guest-mom',
    name: '妈妈',
    avatar: '/avatars/parent/Cute_cartoon_avatar_of_a_young_2026-04-27T18-33-05.png',
    stars: 320,
    role: 'parent',
  },
  {
    id: 'guest-dad',
    name: '爸爸',
    avatar: '/avatars/parent/Cute_cartoon_avatar_of_an_Asia_2026-04-27T18-33-03.png',
    stars: 180,
    role: 'parent',
  },
  {
    id: 'guest-son',
    name: '小明',
    avatar: '/avatars/boy/Cute_cartoon_avatar_of_an_Asia_2026-04-27T18-28-10.png',
    stars: 186,
    role: 'child',
  },
  {
    id: 'guest-daughter',
    name: '小红',
    avatar: '/avatars/girl/Cute_cartoon_avatar_of_an_Asia_2026-04-27T18-30-54.png',
    stars: 254,
    role: 'child',
  },
];

// ========== 游客任务 ==========
// 状态说明：
//   pending   - 待完成（进行中）
//   reviewing - 已提交，待家长审核
//   completed - 已完成（已审核通过）
//   overdue  - 已逾期

export const GUEST_TASKS: Task[] = [
  // ==================== 小明（小学三年级）的任务 ====================

  // Q1 - 紧急重要：明天截止，必须今天完成
  {
    id: 'guest-t1',
    title: '数学作业：两位数乘法',
    description: '完成课本第35页全部练习题，明天上课要交',
    type: 'once',
    startTime: today + 'T09:00:00.000Z',
    endTime: tomorrow + 'T08:00:00.000Z',
    assigneeIds: ['guest-son'],
    creatorId: 'guest-mom',
    rewardStars: 30,
    status: 'pending',
    icon: '/task-icons/study/Cute_flat_kawaii_doing_homewor_2026-04-27T20-18-31.png',
    isHabit: false,
  },
  {
    id: 'guest-t2',
    title: '书法练习：抄写古诗三首',
    description: '用笔抄写《静夜思》《春晓》《悯农》，字迹工整',
    type: 'once',
    startTime: today + 'T14:00:00.000Z',
    endTime: tomorrow + 'T08:00:00.000Z',
    assigneeIds: ['guest-son'],
    creatorId: 'guest-mom',
    rewardStars: 25,
    status: 'pending',
    icon: '/task-icons/study/Cute_flat_kawaii_calligraphy_w_2026-04-27T20-18-14.png',
    isHabit: false,
  },
  // Q1 - 紧急重要：已提交待审核（家长需尽快处理）
  {
    id: 'guest-t3',
    title: '语文阅读理解练习',
    description: '完成练习册第12-13页',
    type: 'once',
    startTime: yesterday + 'T15:00:00.000Z',
    assigneeIds: ['guest-son'],
    creatorId: 'guest-mom',
    rewardStars: 20,
    status: 'reviewing',
    icon: '/task-icons/study/Cute_flat_kawaii_icon_of_readi_2026-04-27T20-17-45.png',
    isHabit: false,
  },

  // Q2 - 不紧急重要：长期习惯，需要坚持
  {
    id: 'guest-t4',
    title: '每日阅读30分钟',
    description: '选择喜欢的课外书，培养阅读习惯',
    type: 'daily',
    frequency: 'daily',
    startTime: today + 'T19:00:00.000Z',
    assigneeIds: ['guest-son'],
    creatorId: 'guest-mom',
    rewardStars: 15,
    status: 'pending',
    icon: '/task-icons/study/Cute_flat_kawaii_icon_of_readi_2026-04-27T20-17-45.png',
    isHabit: true,
    targetCount: 7,
    currentCount: 4,
  },
  {
    id: 'guest-t5',
    title: '跳绳锻炼10分钟',
    description: '每天坚持跳绳，增强体质',
    type: 'daily',
    frequency: 'daily',
    startTime: today + 'T17:00:00.000Z',
    assigneeIds: ['guest-son'],
    creatorId: 'guest-dad',
    rewardStars: 10,
    status: 'pending',
    icon: '/task-icons/life/Cute_flat_kawaii_sports_jump__2026-04-27T20-19-45.png',
    isHabit: true,
    targetCount: 7,
    currentCount: 5,
  },
  {
    id: 'guest-t6',
    title: '准备下月朗诵比赛',
    description: '选一首诗，每天练习10分钟朗诵技巧',
    type: 'once',
    startTime: today + 'T20:00:00.000Z',
    endTime: nextWeek + 'T23:59:59.000Z',
    assigneeIds: ['guest-son'],
    creatorId: 'guest-mom',
    rewardStars: 50,
    status: 'pending',
    icon: '/task-icons/hobby/Cute_flat_kawaii_microphone_s_2026-04-27T20-21-05.png',
    isHabit: false,
  },

  // Q3 - 紧急不重要：同学临时约玩，可推迟
  {
    id: 'guest-t7',
    title: '整理玩具（小明主动说今天要做）',
    description: '把乐高和玩具车归位，但优先级不高',
    type: 'once',
    startTime: today + 'T16:00:00.000Z',
    assigneeIds: ['guest-son'],
    creatorId: 'guest-son',
    rewardStars: 10,
    status: 'pending',
    icon: '/task-icons/independent/Cute_flat_kawaii_packing_schoo_2026-04-27T20-22-27.png',
    isHabit: false,
  },

  // Q4 - 不紧急不重要：玩游戏、看动画片
  {
    id: 'guest-t8',
    title: '看动画片（周末奖励）',
    description: '完成作业后才可以看，每次不超过30分钟',
    type: 'once',
    startTime: tomorrow + 'T18:00:00.000Z',
    assigneeIds: ['guest-son'],
    creatorId: 'guest-mom',
    rewardStars: 0,
    status: 'pending',
    icon: '/task-icons/life/Cute_flat_kawaii_watching_TV__2026-04-27T20-20-10.png',
    isHabit: false,
  },

  // ==================== 小红（初中一年级）的任务 ====================

  // Q1 - 紧急重要：考试复习、截止作业
  {
    id: 'guest-t9',
    title: '数学期中考试复习',
    description: '复习前三章内容，明天上午考试',
    type: 'once',
    startTime: today + 'T19:00:00.000Z',
    endTime: tomorrow + 'T10:00:00.000Z',
    assigneeIds: ['guest-daughter'],
    creatorId: 'guest-mom',
    rewardStars: 50,
    status: 'pending',
    icon: '/task-icons/study/Cute_flat_kawaii_doing_homewor_2026-04-27T20-18-31.png',
    isHabit: false,
  },
  {
    id: 'guest-t10',
    title: '英语作文：My Dream Job',
    description: '不少于120词，后天上课交',
    type: 'once',
    startTime: today + 'T15:00:00.000Z',
    endTime: tomorrow + 'T23:59:59.000Z',
    assigneeIds: ['guest-daughter'],
    creatorId: 'guest-mom',
    rewardStars: 40,
    status: 'pending',
    icon: '/task-icons/study/Cute_flat_kawaii_writing_essay_2026-04-27T20-18-50.png',
    isHabit: false,
  },
  {
    id: 'guest-t11',
    title: '科学实验报告（已提交待审核）',
    description: '种子发芽观察实验，记录7天数据',
    type: 'once',
    startTime: yesterday + 'T16:00:00.000Z',
    assigneeIds: ['guest-daughter'],
    creatorId: 'guest-daughter',
    rewardStars: 35,
    status: 'reviewing',
    icon: '/task-icons/study/Cute_flat_kawaii_science_exper_2026-04-27T20-19-20.png',
    isHabit: false,
  },

  // Q2 - 不紧急重要：长期积累
  {
    id: 'guest-t12',
    title: '英语单词背诵20个',
    description: '每天背诵并默写，长期积累很重要',
    type: 'daily',
    frequency: 'daily',
    startTime: today + 'T07:00:00.000Z',
    assigneeIds: ['guest-daughter'],
    creatorId: 'guest-mom',
    rewardStars: 20,
    status: 'pending',
    icon: '/task-icons/study/Cute_flat_kawaii_English_vocab_2026-04-27T20-17-50.png',
    isHabit: true,
    targetCount: 30,
    currentCount: 12,
  },
  {
    id: 'guest-t13',
    title: '练习小提琴30分钟',
    description: '坚持练习音阶和练习曲',
    type: 'daily',
    frequency: 'daily',
    startTime: today + 'T18:00:00.000Z',
    assigneeIds: ['guest-daughter'],
    creatorId: 'guest-dad',
    rewardStars: 30,
    status: 'pending',
    icon: '/task-icons/hobby/Cute_flat_kawai_piano_playing__2026-04-27T20-21-20.png',
    isHabit: true,
    targetCount: 7,
    currentCount: 3,
  },
  {
    id: 'guest-t14',
    title: '跑步锻炼20分钟',
    description: '中考体育要考800米，平时多练习',
    type: 'daily',
    frequency: 'daily',
    startTime: today + 'T06:30:00.000Z',
    assigneeIds: ['guest-daughter'],
    creatorId: 'guest-dad',
    rewardStars: 15,
    status: 'pending',
    icon: '/task-icons/life/Cute_flat_kawaii_sports_runni_2026-04-27T20-19-45.png',
    isHabit: true,
    targetCount: 5,
    currentCount: 2,
  },
  {
    id: 'guest-t15',
    title: '课外阅读：《朝花夕拾》',
    description: '本周读完前两章，写100字读后感',
    type: 'once',
    startTime: today + 'T20:00:00.000Z',
    endTime: nextWeek + 'T23:59:59.000Z',
    assigneeIds: ['guest-daughter'],
    creatorId: 'guest-mom',
    rewardStars: 40,
    status: 'pending',
    icon: '/task-icons/study/Cute_flat_kawaii_reading_book__2026-04-27T20-17-30.png',
    isHabit: false,
  },

  // Q3 - 紧急不重要：社交干扰
  {
    id: 'guest-t16',
    title: '回复同学群消息',
    description: '讨论周末聚会安排，可稍后处理',
    type: 'once',
    startTime: today + 'T12:00:00.000Z',
    assigneeIds: ['guest-daughter'],
    creatorId: 'guest-daughter',
    rewardStars: 0,
    status: 'pending',
    icon: '/task-icons/life/Cute_flat_kawaii_chatting_with_2026-04-27T20-20-50.png',
    isHabit: false,
  },

  // Q4 - 不紧急不重要：刷短视频、追剧
  {
    id: 'guest-t17',
    title: '刷短视频（限时15分钟）',
    description: '完成作业后可以适当放松，注意控制时间',
    type: 'once',
    startTime: tomorrow + 'T21:00:00.000Z',
    assigneeIds: ['guest-daughter'],
    creatorId: 'guest-daughter',
    rewardStars: -5,
    status: 'pending',
    icon: '/task-icons/life/Cute_flat_kawaii_watching_TV__2026-04-27T20-20-10.png',
    isHabit: false,
  },

  // ==================== 已完成的任务（历史） ====================
  {
    id: 'guest-t18',
    title: '收拾书包（已完成）',
    description: '把明天的课本和文具整理好',
    type: 'daily',
    frequency: 'daily',
    startTime: yesterday + 'T20:00:00.000Z',
    assigneeIds: ['guest-son', 'guest-daughter'],
    creatorId: 'guest-mom',
    rewardStars: 10,
    status: 'completed',
    icon: '/task-icons/independent/Cute_flat_kawaii_packing_schoo_2026-04-27T20-22-27.png',
    isHabit: false,
  },
];

// ========== 游客习惯（奖惩卡片） ==========
export const GUEST_HABITS: Task[] = [
  // 积极习惯
  {
    id: 'guest-h1',
    title: '每日早起（7:00前）',
    description: '不迟到，养成良好作息习惯',
    type: 'daily',
    frequency: 'daily',
    startTime: today + 'T07:00:00.000Z',
    assigneeIds: ['guest-son', 'guest-daughter'],
    creatorId: 'guest-mom',
    rewardStars: 10,
    status: 'pending',
    icon: '/task-icons/life/Cute_flat_kawaii_waking_up_ear_2026-04-27T20-20-31.png',
    isHabit: true,
    targetCount: 7,
    currentCount: 5,
  },
  {
    id: 'guest-h2',
    title: '每天喝水8杯',
    description: '保持健康饮水习惯',
    type: 'daily',
    frequency: 'daily',
    startTime: today + 'T08:00:00.000Z',
    assigneeIds: ['guest-son', 'guest-daughter'],
    creatorId: 'guest-mom',
    rewardStars: 5,
    status: 'pending',
    icon: '/task-icons/life/Cute_flat_kawaii_drinking_wate_2026-04-27T20-19-03.png',
    isHabit: true,
    targetCount: 8,
    currentCount: 4,
  },
  {
    id: 'guest-h3',
    title: '老师表扬',
    description: '在学校表现好，得到老师表扬',
    type: 'once',
    startTime: today + 'T10:00:00.000Z',
    assigneeIds: ['guest-son', 'guest-daughter'],
    creatorId: 'guest-mom',
    rewardStars: 50,
    status: 'pending',
    icon: '/task-icons/praise/Cute_flat_kawaii_icon_of_teach_2026-04-27T20-11-28.png',
    isHabit: true,
    targetCount: 1,
    currentCount: 0,
  },
  // 消极习惯（惩罚）
  {
    id: 'guest-h4',
    title: '晚睡（超过22:00）',
    description: '早睡早起身体好，晚睡要扣星星',
    type: 'daily',
    frequency: 'daily',
    startTime: today + 'T22:00:00.000Z',
    assigneeIds: ['guest-son', 'guest-daughter'],
    creatorId: 'guest-mom',
    rewardStars: -15,
    status: 'pending',
    icon: '/task-icons/critique/Cute_flat_kawaii_icon_of_stayi_2026-04-27T20-09-38.png',
    isHabit: true,
    targetCount: 1,
    currentCount: 0,
  },
  {
    id: 'guest-h5',
    title: '挑食',
    description: '不挑食才能长高高、长壮壮',
    type: 'daily',
    frequency: 'daily',
    startTime: today + 'T12:00:00.000Z',
    assigneeIds: ['guest-son'],
    creatorId: 'guest-mom',
    rewardStars: -10,
    status: 'pending',
    icon: '/task-icons/critique/Cute_flat_kawaii_icon_of_picky_2026-04-27T20-09-54.png',
    isHabit: true,
    targetCount: 1,
    currentCount: 0,
  },
  {
    id: 'guest-h6',
    title: '玩手机超时',
    description: '每天使用手机不超过30分钟',
    type: 'daily',
    frequency: 'daily',
    startTime: today + 'T21:00:00.000Z',
    assigneeIds: ['guest-daughter'],
    creatorId: 'guest-mom',
    rewardStars: -20,
    status: 'pending',
    icon: '/task-icons/critique/Cute_flat_kawaii_icon_of_using__2026-04-27T20-10-10.png',
    isHabit: true,
    targetCount: 1,
    currentCount: 0,
  },
];

// ========== 游客心愿/奖励 ==========
export const GUEST_REWARDS: Reward[] = [
  {
    id: 'guest-r1',
    name: '看电视',
    description: '自由观看一小时喜欢的电视节目',
    cost: 30,
    icon: '/reward-icons/common/A_cute_flat_design_kawaii_styl_2026-04-27T19-41-31.png',
    image: '',
    category: '常用',
  },
  {
    id: 'guest-r2',
    name: '冰淇淋',
    description: '享用一个大号冰淇淋',
    cost: 40,
    icon: '/reward-icons/privilege/Cute_flat_kawaii_ice_cream_con_2026-04-27T20-45-45.png',
    image: '',
    category: '特权',
  },
  {
    id: 'guest-r3',
    name: '玩游戏',
    description: '畅玩电子游戏一小时',
    cost: 50,
    icon: '/reward-icons/prize/Cute_flat_kawaii_video_game_co_2026-04-27T19-44-07.png',
    image: '',
    category: '奖品',
  },
  {
    id: 'guest-r4',
    name: '家庭电影夜',
    description: '全家一起看电影，配爆米花和饮料',
    cost: 200,
    icon: '/reward-icons/experience/A_cute_flat_design_kawaii_styl_2026-04-27T19-42-17.png',
    image: '',
    category: '体验',
  },
  {
    id: 'guest-r5',
    name: '乐高套装',
    description: '购买一套乐高积木玩具',
    cost: 400,
    icon: '/reward-icons/activity/Cute_flat_kawaii_LEGO_building_2026-04-27T19-48-32.png',
    image: '',
    category: '活动',
  },
  {
    id: 'guest-r6',
    name: '储零花钱',
    description: '获得一笔可以自由支配的零花钱',
    cost: 100,
    icon: '/reward-icons/common/A_cute_flat_design_kawaii_styl_2026-04-27T19-41-28.png',
    image: '',
    category: '常用',
  },
  {
    id: 'guest-r7',
    name: '游乐园',
    description: '去游乐园玩一整天！',
    cost: 1000,
    icon: '/reward-icons/experience/Cute_flat_kawaii_amusement_par_2026-04-27T19-43-16.png',
    image: '',
    category: '体验',
  },
  {
    id: 'guest-r8',
    name: '北京环球影城',
    description: '去北京环球影城畅玩一天！',
    cost: 3000,
    icon: '/reward-icons/activity/Cute_flat_kawaii_Universal_Stu_2026-04-27T19-47-50.png',
    image: '',
    category: '活动',
    stock: 2,
  },
  {
    id: 'guest-r9',
    name: '骑行郊游',
    description: '全家一起去骑自行车郊游',
    cost: 100,
    icon: '/reward-icons/growth/Cute_flat_kawaii_cycling_bike__2026-04-27T19-46-53.png',
    image: '',
    category: '成长',
  },
  {
    id: 'guest-r10',
    name: '肯德基全家桶',
    description: '享用一次肯德基全家桶套餐',
    cost: 150,
    icon: '/reward-icons/privilege/Cute_flat_kawaii_KFC_fried_chi_2026-04-27T19-44-47.png',
    image: '',
    category: '特权',
  },
];

// ========== 游客历史记录 ==========
export const GUEST_HISTORY: HistoryRecord[] = [
  {
    id: 'guest-hist1',
    userId: 'guest-son',
    title: '完成习惯: 每日早起',
    type: 'task',
    stars: 10,
    timestamp: today + 'T07:15:00.000Z',
    icon: 'Sun',
  },
  {
    id: 'guest-hist2',
    userId: 'guest-son',
    title: '完成任务: 收拾书包',
    type: 'task',
    stars: 10,
    timestamp: yesterday + 'T20:30:00.000Z',
    icon: 'CheckCircle',
  },
  {
    id: 'guest-hist3',
    userId: 'guest-daughter',
    title: '完成习惯: 练习小提琴',
    type: 'task',
    stars: 30,
    timestamp: yesterday + 'T18:30:00.000Z',
    icon: 'Music',
  },
  {
    id: 'guest-hist4',
    userId: 'guest-daughter',
    title: '完成任务: 英语单词背诵',
    type: 'task',
    stars: 20,
    timestamp: yesterday + 'T07:30:00.000Z',
    icon: 'Languages',
  },
  {
    id: 'guest-hist5',
    userId: 'guest-son',
    title: '完成习惯: 每天喝水8杯',
    type: 'task',
    stars: 5,
    timestamp: yesterday + 'T18:00:00.000Z',
    icon: 'Droplets',
  },
  {
    id: 'guest-hist6',
    userId: 'guest-son',
    title: '老师表扬: 课堂积极发言',
    type: 'task',
    stars: 50,
    timestamp: yesterday + 'T10:30:00.000Z',
    icon: 'Award',
  },
  {
    id: 'guest-hist7',
    userId: 'guest-daughter',
    title: '兑换心愿: 看电视',
    type: 'redeem',
    stars: -30,
    timestamp: yesterday + 'T19:00:00.000Z',
    icon: 'Gift',
  },
  {
    id: 'guest-hist8',
    userId: 'guest-son',
    title: '完成任务: 数学作业',
    type: 'task',
    stars: 30,
    timestamp: yesterday + 'T16:00:00.000Z',
    icon: 'BookOpen',
  },
  {
    id: 'guest-hist9',
    userId: 'guest-daughter',
    title: '惩罚: 玩手机超时',
    type: 'penalty',
    stars: -20,
    timestamp: yesterday + 'T22:30:00.000Z',
    icon: 'Smartphone',
  },
];

/** 获取所有游客展示数据 */
export function getGuestData() {
  return {
    members: GUEST_MEMBERS,
    tasks: [...GUEST_TASKS, ...GUEST_HABITS],
    rewards: GUEST_REWARDS,
    history: GUEST_HISTORY,
  };
}
