/**
 * 游客模式展示数据
 * 纯前端本地数据，不需要数据库连接
 * 让新用户在注册前就能体验完整功能
 */
import { Task, Member, Reward, HistoryRecord } from '../types';

const now = new Date();
const today = now.toISOString().split('T')[0];
const yesterday = new Date(now.getTime() - 86400000).toISOString().split('T')[0];
const twoDaysAgo = new Date(now.getTime() - 86400000 * 2).toISOString().split('T')[0];

// ========== 游客家庭成员 ==========
export const GUEST_MEMBERS: Member[] = [
  {
    id: 'guest-mom',
    name: '妈妈',
    avatar: '/avatars/parent/Cute_cartoon_avatar_of_a_young_2026-04-27T18-33-05.png',
    stars: 320,
    role: 'parent',
  },
  {
    id: 'guest-dad',
    name: '爸爸',
    avatar: '/avatars/parent/Cute_cartoon_avatar_of_an_Asia_2026-04-27T18-33-03.png',
    stars: 180,
    role: 'parent',
  },
  {
    id: 'guest-child',
    name: '小明',
    avatar: '/avatars/boy/Cute_cartoon_avatar_of_an_Asia_2026-04-27T18-28-10.png',
    stars: 256,
    role: 'child',
  },
  {
    id: 'guest-girl',
    name: '小花',
    avatar: '/avatars/girl/Cute_cartoon_avatar_of_an_Asia_2026-04-27T18-30-54.png',
    stars: 198,
    role: 'child',
  },
];

// ========== 游客任务 ==========
export const GUEST_TASKS: Task[] = [
  {
    id: 'guest-t1',
    title: '做作业',
    description: '完成今天的语文和数学作业，字迹工整',
    type: 'daily',
    frequency: 'daily',
    startTime: new Date(now.getTime() - 3600000 * 2).toISOString(),
    assigneeIds: ['guest-child'],
    creatorId: 'guest-mom',
    rewardStars: 50,
    status: 'pending',
    icon: '/task-icons/study/Cute_flat_kawaii_doing_homewor_2026-04-27T20-18-31.png',
  },
  {
    id: 'guest-t2',
    title: '阅读30分钟',
    description: '选择一本喜欢的课外书安静阅读',
    type: 'daily',
    frequency: 'daily',
    startTime: new Date(now.getTime() - 3600000 * 4).toISOString(),
    assigneeIds: ['guest-child', 'guest-girl'],
    creatorId: 'guest-mom',
    rewardStars: 40,
    status: 'pending',
    icon: '/task-icons/study/Cute_flat_kawaii_icon_of_readi_2026-04-27T20-17-45.png',
  },
  {
    id: 'guest-t3',
    title: '练字',
    description: '认真书写两页字帖，注意笔画顺序',
    type: 'daily',
    frequency: 'daily',
    startTime: new Date(now.getTime() - 3600000 * 5).toISOString(),
    assigneeIds: ['guest-child'],
    creatorId: 'guest-dad',
    rewardStars: 30,
    status: 'reviewing',
    icon: '/task-icons/study/Cute_flat_kawaii_calligraphy_w_2026-04-27T20-18-14.png',
  },
  {
    id: 'guest-t4',
    title: '收拾书包',
    description: '把明天的课本和文具整理好放进书包',
    type: 'daily',
    frequency: 'daily',
    startTime: yesterday + 'T20:00:00.000Z',
    assigneeIds: ['guest-child', 'guest-girl'],
    creatorId: 'guest-mom',
    rewardStars: 20,
    status: 'completed',
    icon: '/task-icons/independent/Cute_flat_kawaii_packing_schoo_2026-04-27T20-22-27.png',
  },
  {
    id: 'guest-t5',
    title: '刷牙洗脸',
    description: '早晚认真刷牙两分钟，保持口腔卫生',
    type: 'daily',
    frequency: 'daily',
    startTime: yesterday + 'T07:00:00.000Z',
    assigneeIds: ['guest-girl'],
    creatorId: 'guest-mom',
    rewardStars: 10,
    status: 'completed',
    icon: '/task-icons/life/Cute_flat_kawaii_brushing_teet_2026-04-27T20-20-31.png',
  },
];

// ========== 游客习惯 ==========
export const GUEST_HABITS: Task[] = [
  {
    id: 'guest-h1',
    title: '每日早起',
    description: '每天早上7点前起床，养成早起好习惯',
    type: 'daily',
    frequency: 'daily',
    startTime: twoDaysAgo + 'T07:00:00.000Z',
    assigneeIds: ['guest-child'],
    creatorId: 'guest-mom',
    rewardStars: 20,
    status: 'pending',
    icon: '/task-icons/life/Cute_flat_kawaii_waking_up_ear_2026-04-27T20-20-31.png',
    isHabit: true,
    targetCount: 7,
    currentCount: 4,
  },
  {
    id: 'guest-h2',
    title: '多喝水',
    description: '每天喝8杯水，保持身体健康',
    type: 'daily',
    frequency: 'daily',
    startTime: twoDaysAgo + 'T08:00:00.000Z',
    assigneeIds: ['guest-child', 'guest-girl'],
    creatorId: 'guest-mom',
    rewardStars: 10,
    status: 'pending',
    icon: '/task-icons/life/Cute_flat_kawaii_drinking_wate_2026-04-27T20-19-03.png',
    isHabit: true,
    targetCount: 8,
    currentCount: 5,
  },
  {
    id: 'guest-h3',
    title: '弹钢琴',
    description: '每天练习钢琴30分钟',
    type: 'daily',
    frequency: 'daily',
    startTime: twoDaysAgo + 'T16:00:00.000Z',
    assigneeIds: ['guest-girl'],
    creatorId: 'guest-dad',
    rewardStars: 50,
    status: 'pending',
    icon: '/task-icons/hobby/Cute_flat_kawai_piano_playing__2026-04-27T20-21-20.png',
    isHabit: true,
    targetCount: 5,
    currentCount: 3,
  },
  {
    id: 'guest-h4',
    title: '老师表扬',
    description: '在学校得到老师表扬',
    type: 'daily',
    frequency: 'daily',
    startTime: yesterday + 'T10:00:00.000Z',
    assigneeIds: ['guest-child'],
    creatorId: 'guest-mom',
    rewardStars: 50,
    status: 'pending',
    icon: '/task-icons/praise/Cute_flat_kawaii_icon_of_teach_2026-04-27T20-11-28.png',
    isHabit: true,
    targetCount: 1,
    currentCount: 0,
  },
  {
    id: 'guest-h5',
    title: '晚睡',
    description: '超过10点还没睡觉要扣星星哦',
    type: 'daily',
    frequency: 'daily',
    startTime: twoDaysAgo + 'T22:00:00.000Z',
    assigneeIds: ['guest-child', 'guest-girl'],
    creatorId: 'guest-mom',
    rewardStars: -20,
    status: 'pending',
    icon: '/task-icons/critique/Cute_flat_kawaii_icon_of_stayi_2026-04-27T20-09-38.png',
    isHabit: true,
    targetCount: 1,
    currentCount: 0,
  },
  {
    id: 'guest-h6',
    title: '挑食',
    description: '不挑食才能长高高',
    type: 'daily',
    frequency: 'daily',
    startTime: twoDaysAgo + 'T12:00:00.000Z',
    assigneeIds: ['guest-girl'],
    creatorId: 'guest-mom',
    rewardStars: -10,
    status: 'pending',
    icon: '/task-icons/critique/Cute_flat_kawaii_icon_of_picky_2026-04-27T20-09-54.png',
    isHabit: true,
    targetCount: 1,
    currentCount: 0,
  },
];

// ========== 游客心愿/奖励 ==========
export const GUEST_REWARDS: Reward[] = [
  {
    id: 'guest-r1',
    name: '看电视',
    description: '自由观看一小时喜欢的电视节目',
    cost: 30,
    icon: '/reward-icons/common/A_cute_flat_design_kawaii_styl_2026-04-27T19-41-31.png',
    image: '',
    category: '常用',
  },
  {
    id: 'guest-r2',
    name: '冰淇淋',
    description: '享用一个大号冰淇淋',
    cost: 40,
    icon: '/reward-icons/privilege/Cute_flat_kawaii_ice_cream_con_2026-04-27T20-45-45.png',
    image: '',
    category: '特权',
  },
  {
    id: 'guest-r3',
    name: '玩游戏',
    description: '畅玩电子游戏一小时',
    cost: 50,
    icon: '/reward-icons/prize/Cute_flat_kawaii_video_game_co_2026-04-27T19-44-07.png',
    image: '',
    category: '奖品',
  },
  {
    id: 'guest-r4',
    name: '家庭电影',
    description: '全家一起看电影，配爆米花和饮料',
    cost: 200,
    icon: '/reward-icons/experience/A_cute_flat_design_kawaii_styl_2026-04-27T19-42-17.png',
    image: '',
    category: '体验',
  },
  {
    id: 'guest-r5',
    name: '乐高',
    description: '购买一套乐高积木玩具',
    cost: 400,
    icon: '/reward-icons/activity/Cute_flat_kawaii_LEGO_building_2026-04-27T19-48-32.png',
    image: '',
    category: '活动',
  },
  {
    id: 'guest-r6',
    name: '储零花钱',
    description: '获得一笔可以自由支配的零花钱',
    cost: 100,
    icon: '/reward-icons/common/A_cute_flat_design_kawaii_styl_2026-04-27T19-41-28.png',
    image: '',
    category: '常用',
  },
  {
    id: 'guest-r7',
    name: '游乐园',
    description: '去游乐园玩一整天！',
    cost: 1000,
    icon: '/reward-icons/experience/Cute_flat_kawaii_amusement_par_2026-04-27T19-43-16.png',
    image: '',
    category: '体验',
  },
  {
    id: 'guest-r8',
    name: '北京环球影城',
    description: '去北京环球影城畅玩一天！',
    cost: 3000,
    icon: '/reward-icons/activity/Cute_flat_kawaii_Universal_Stu_2026-04-27T19-47-50.png',
    image: '',
    category: '活动',
    stock: 2,
  },
  {
    id: 'guest-r9',
    name: '骑行',
    description: '全家一起去骑自行车郊游',
    cost: 100,
    icon: '/reward-icons/growth/Cute_flat_kawaii_cycling_bike__2026-04-27T19-46-53.png',
    image: '',
    category: '成长',
  },
  {
    id: 'guest-r10',
    name: '肯德基',
    description: '享用一次肯德基套餐',
    cost: 150,
    icon: '/reward-icons/privilege/Cute_flat_kawaii_KFC_fried_chi_2026-04-27T19-44-47.png',
    image: '',
    category: '特权',
  },
];

// ========== 游客历史记录 ==========
export const GUEST_HISTORY: HistoryRecord[] = [
  {
    id: 'guest-hist1',
    userId: 'guest-child',
    title: '完成习惯: 每日早起',
    type: 'task',
    stars: 20,
    timestamp: today + 'T07:15:00.000Z',
    icon: 'Sun',
  },
  {
    id: 'guest-hist2',
    userId: 'guest-child',
    title: '完成任务: 收拾书包',
    type: 'task',
    stars: 20,
    timestamp: yesterday + 'T20:30:00.000Z',
    icon: 'CheckCircle',
  },
  {
    id: 'guest-hist3',
    userId: 'guest-girl',
    title: '完成习惯: 弹钢琴',
    type: 'task',
    stars: 50,
    timestamp: yesterday + 'T17:00:00.000Z',
    icon: 'Music',
  },
  {
    id: 'guest-hist4',
    userId: 'guest-girl',
    title: '完成任务: 刷牙洗脸',
    type: 'task',
    stars: 10,
    timestamp: yesterday + 'T07:10:00.000Z',
    icon: 'CheckCircle',
  },
  {
    id: 'guest-hist5',
    userId: 'guest-child',
    title: '完成习惯: 多喝水',
    type: 'task',
    stars: 10,
    timestamp: yesterday + 'T12:00:00.000Z',
    icon: 'Droplets',
  },
  {
    id: 'guest-hist6',
    userId: 'guest-child',
    title: '老师表扬: 课堂积极发言',
    type: 'task',
    stars: 50,
    timestamp: twoDaysAgo + 'T10:30:00.000Z',
    icon: 'Award',
  },
  {
    id: 'guest-hist7',
    userId: 'guest-girl',
    title: '兑换心愿: 看电视',
    type: 'redeem',
    stars: -30,
    timestamp: twoDaysAgo + 'T18:00:00.000Z',
    icon: 'Gift',
  },
  {
    id: 'guest-hist8',
    userId: 'guest-child',
    title: '完成任务: 做作业',
    type: 'task',
    stars: 50,
    timestamp: twoDaysAgo + 'T16:00:00.000Z',
    icon: 'BookOpen',
  },
];

/** 获取所有游客展示数据 */
export function getGuestData() {
  return {
    members: GUEST_MEMBERS,
    tasks: [...GUEST_TASKS, ...GUEST_HABITS],
    rewards: GUEST_REWARDS,
    history: GUEST_HISTORY,
  };
}
