export const UI_TOKENS = {
  color: {
    light: {
      primary: '#006e1c',
      primaryContainer: '#4caf50',
      secondary: '#686000',
      secondaryContainer: '#f0e269',
      background: '#fbf9f5',
      surface: '#fbf9f5',
      surfaceContainerLow: '#f5f3ef',
      surfaceContainer: '#efeeea',
      surfaceContainerHigh: '#eae8e4',
      surfaceContainerHighest: '#e4e2de',
      onSurface: '#1b1c1a',
      onSurfaceVariant: '#3f4a3c',
      outline: '#6f7a6b',
      outlineVariant: '#becab9',
    },
    dark: {
      primary: '#81d67a',
      primaryContainer: '#008126',
      secondary: '#f0e269',
      secondaryContainer: '#3f4a3c',
      background: '#1b1c1a',
      surface: '#1b1c1a',
      surfaceContainerLow: '#242522',
      surfaceContainer: '#2b2c29',
      surfaceContainerHigh: '#31322f',
      surfaceContainerHighest: '#373834',
      onSurface: '#e4e2de',
      onSurfaceVariant: '#becab9',
      outline: '#6f7a6b',
      outlineVariant: '#becab9',
    },
    semantic: {
      q1: '#E57373',
      q2: '#64B5F6',
      q3: '#FFD54F',
      q4: '#90A4AE',
      pending: '#FFB74D',
      inProgress: '#4FC3F7',
      reviewing: '#BA68C8',
      completed: '#81C784',
      reward: '#FFD600',
      rewardDeep: '#F9A825',
      rewardDisplay: '#FBC02D',
      danger: '#E57373',
      avatarPalette: ['#FF6B6B', '#FFA726', '#66BB6A', '#42A5F5', '#AB47BC', '#EC407A', '#26C6DA', '#8D6E63'],
      avatarReadableLightBackgrounds: ['#FFEE58', '#FFF176', '#66BB6A'],
      avatarTextOnLight: '#333333',
      avatarTextOnDark: '#FFFFFF',
    },
  },
  radius: {
    small: 8,
    medium: 16,
    large: 24,
    full: 9999,
  },
  spacing: [4, 8, 12, 16, 20, 24, 32, 40, 48, 64],
  touch: {
    minimum: 44,
  },
  navigation: {
    tabs: [
      { id: 'home', label: '首页', path: '/' },
      { id: 'tasks', label: '任务', path: '/tasks' },
      { id: 'habits', label: '奖惩', path: '/habits', highlight: true },
      { id: 'rewards', label: '心愿', path: '/rewards' },
      { id: 'profile', label: '我的', path: '/profile' },
    ],
  },
} as const;

export type UiTokens = typeof UI_TOKENS;
